(function (a,b) {
    console.log(a+b);
})(2,43)
// no need of the function name...(in invoked function)
// In arrow function have not need to function name....
// In anonymous have also not need to function name....